export enum DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
}

export enum PERIODICITY {
  WEEKLY = 1,
  BIWEEKLY = 2,
}

export enum GRID_STATE {
  OPEN = "OPEN",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED",
}
