export enum DURATION {
  FIFTEEN_MINUTES = "00:15",
  THIRTY_MINUTES = "00:30",
  FOURTYFIVE_MINUTES = "00:45",
  ONE_HOUR = "01:00",
}

export enum DAY {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
}

export enum PERIODICITY {
  WEEKLY = 1,
  BIWEEKLY = 2,
}

export enum GRID_STATE {
  OPEN = "OPEN",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED",
}
